name: Build Minecraft

on:
  pull_request:
    branches: [trunk, rendering-dev]
  push:
    branches: [trunk, rendering-dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Build
        run: python3 ./scripts/make-minecraft.py